## 20.09.28 월요일 django rest-auth 사용시 회원탈퇴

#### User 모델 delete() 시 에러 발생

- `django.db.utils.OperationalError: no such table: allauth_socialaccount` 에러가 발생했다.



#### INSTALLED_APPS에 필요한 항목들

- ```python
  'allauth',
  'allauth.account',
  'allauth.socialaccount',
  'allauth.socialaccount.providers.openid',
  ```

- 위의 4개 항목이 전부 있어야 user 모델에서 delete()를 사용 가능했다

- 기존에는 `'allauth.socialaccount', 'allauth.socialaccount.providers.openid',` 의 2개 항목이 없었고, 그로 인해 에러가 발생했다.