## 20.10.22 목요일 ubuntu에서 django 실행 시 연결 거부

#### 일반적인 실행

- 로컬에서 돌리듯 `python manage.py runserver`로 실행할 경우
  - 접속 주소가 `127.0.0.1:8000`으로 나오면서 접속이 불가능하다
- `python3 manage.py runserver 0:8000`으로 실행
  - 이 경우 기존 발급받은 주소(서버명, dns)로 접속할 수 있다
  - ex) `http://k3d201.p.ssafy.io:8000/swagger/`